# Generated by Django 3.1 on 2020-08-26 01:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200826_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='categories',
            field=models.CharField(choices=[('education', 'education'), ('lifestyle', 'lifestyle'), ('programming', 'programming'), ('music', 'music')], default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
