# Generated by Django 3.1 on 2020-08-26 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200826_0245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcoment',
            old_name='user',
            new_name='author',
        ),
    ]
