# Generated by Django 3.1 on 2020-08-26 02:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20200826_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('education', 'education'), ('lifestyle', 'lifestyle'), ('programming', 'programming'), ('music', 'music')], default='general', max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='BlogComent',
            new_name='BlogComment',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='categories',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default='general', max_length=255),
        ),
    ]
