# Generated by Django 3.1 on 2020-08-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200826_0352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(max_length=10000, verbose_name='blog content'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='category',
            field=models.CharField(default='general', max_length=255, unique=True),
        ),
    ]
